const destinationData={
  mexico:{name:'Mexico',price:'$1,399',image:'../assets/destinations/mexico.jpg',alt:'Riviera Maya resort on a turquoise Caribbean cove',intro:'Caribbean beaches, cenotes, lively resort towns and a broad range of all-inclusive stays make Mexico an easy place to match with different travel styles.',airline:'Canadian leisure and scheduled carriers',resort:'Riviera Maya and coastal resort options',meal:'All-inclusive options available',gallery:[['../assets/destinations/mexico.jpg','Riviera Maya coastline and resort'],['../assets/packages/riviera-maya/riviera-maya-beach-week-v1.png','Aerial view of a Riviera Maya resort coast'],['../assets/campaign/mexico.jpg','Turquoise water and tropical landscape in Mexico']]},
  'dominican-republic':{name:'Dominican Republic',price:'$1,295',image:'../assets/destinations/dominican-republic.jpg',alt:'Dominican Republic oceanfront resort',intro:'From La Romana to Punta Cana, the Dominican Republic pairs long beaches with varied resort styles, easy all-inclusive planning and options for couples, families and groups.',airline:'Canadian leisure and scheduled carriers',resort:'La Romana, Punta Cana and Puerto Plata options',meal:'All-inclusive options available',gallery:[['../assets/destinations/dominican-republic.jpg','Oceanfront resort in the Dominican Republic'],['../assets/packages/hm-alma-de-bayahibe/ocean-pools.jpg','Oceanfront pools at HM Alma de Bayahibe'],['../assets/packages/hm-alma-de-bayahibe/ocean-view-room.jpg','Ocean-view resort room']]},
  cuba:{name:'Cuba',price:'$999',image:'../assets/destinations/cuba.jpg',alt:'White beach and resort in Varadero, Cuba',intro:'Cuba offers long white-sand beaches, warm water and straightforward resort stays, with Varadero and the cayes remaining favourite options for a simple sun escape.',airline:'Canadian leisure carrier options',resort:'Varadero and island-caye resort options',meal:'All-inclusive options available',gallery:[['../assets/destinations/cuba.jpg','White-sand resort beach in Cuba'],['../assets/destinations/cuba/resort-pool.jpg','Varadero resort pool near the sea'],['../assets/destinations/cuba/resort-room.jpg','Varadero resort room with an ocean view']]},
  jamaica:{name:'Jamaica',price:'$1,499',image:'../assets/destinations/jamaica.jpg',alt:'Cliffside resort and clear cove in Jamaica',intro:'Jamaica brings together cliffside swimming, relaxed beaches, distinctive local culture and resort areas with different energy—from Negril sunsets to Montego Bay convenience.',airline:'Canadian leisure and scheduled carriers',resort:'Negril, Montego Bay and Ocho Rios options',meal:'All-inclusive options available',gallery:[['../assets/destinations/jamaica.jpg','Cliffside resort and cove in Jamaica'],['../assets/destinations/jamaica/resort-pool.jpg','Negril cliffside resort pool'],['../assets/destinations/jamaica/resort-room.jpg','Jamaican resort room at sunset']]},
  cancun:{name:'Cancún',price:'$1,449',image:'../assets/destinations/cancun.jpg',alt:'Cancun hotel zone beside turquoise Caribbean water',intro:'Cancún combines a striking Caribbean coastline with a deep choice of resorts, dining and entertainment, plus easy access to Riviera Maya experiences.',airline:'Direct and connecting options from Canadian gateways',resort:'Hotel Zone and nearby Riviera Maya options',meal:'All-inclusive and breakfast-plan options',gallery:[['../assets/destinations/cancun.jpg','Cancun hotel zone and Caribbean shoreline'],['../assets/destinations/mexico.jpg','Turquoise cove on the Mexican Caribbean'],['../assets/packages/riviera-maya/riviera-maya-beach-week-v1.png','Riviera Maya coastline and resort']]},
  'punta-cana':{name:'Punta Cana',price:'$1,405',image:'../assets/destinations/punta-cana.jpg',alt:'Palm-lined resort beach in Punta Cana',intro:'Punta Cana is built for uncomplicated beach time, with palm-lined shores, a wide range of all-inclusive resorts and choices for adults, families and groups.',airline:'Canadian leisure and scheduled carriers',resort:'Bávaro and Punta Cana resort options',meal:'All-inclusive options available',gallery:[['../assets/destinations/punta-cana.jpg','Palm-lined beach in Punta Cana'],['../assets/destinations/punta-cana/resort-pool.jpg','Punta Cana resort pool beside the beach'],['../assets/destinations/punta-cana/resort-room.jpg','Punta Cana resort room with a palm-framed balcony']]}
};
const key=document.body.dataset.destination;
const data=destinationData[key];
if(data){
  document.title=`${data.name} Vacations — AMAX Vacations`;
  document.querySelector('#detail-image').src=data.image;document.querySelector('#detail-image').alt=data.alt;
  document.querySelector('#detail-title').textContent=`${data.name} Vacations`;
  document.querySelector('#detail-intro').textContent=data.intro;
  document.querySelector('#detail-overview').textContent=data.intro;
  document.querySelector('#detail-airline').textContent=data.airline;
  document.querySelector('#detail-resort').textContent=data.resort;
  document.querySelector('#detail-meal').textContent=data.meal;
  document.querySelectorAll('[data-price]').forEach(el=>el.textContent=data.price);
  const gallery=document.querySelector('#detail-gallery');
  data.gallery.forEach(([src,alt])=>{const figure=document.createElement('figure'),img=document.createElement('img');img.src=src;img.alt=alt;img.width=1800;img.height=1200;img.loading='lazy';figure.append(img);gallery.append(figure)});
  const text=encodeURIComponent(`Hi AMAX Vacations — I’m interested in ${data.name}. Please help me confirm dates, resort options and the current starting price.`);
  document.querySelectorAll('[data-whatsapp]').forEach(link=>link.href=`https://wa.me/14377702030?text=${text}`);
}
const menuButton=document.querySelector('.menu-button'),siteNav=document.querySelector('.site-nav');
const menuLabel=menuButton?.querySelector('.sr-only');
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));if(menuLabel)menuLabel.textContent=open?'Close menu':'Open menu';siteNav?.classList.toggle('is-open',open)});
