document.querySelector('#detail-app').innerHTML=`
  <a class="skip-link" href="#overview">Skip to vacation details</a>
  <div class="announcement"><p>Canada <span aria-hidden="true">→</span> personal vacation planning</p><a data-whatsapp href="#">Talk to an advisor</a></div>
  <header class="site-header"><a class="brand" href="../index.html" aria-label="AMAX Vacations home"><img class="brand-logo" src="../assets/logo/amax-logo-color.png" alt="AMAX Vacations" width="1774" height="887"></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="site-nav"><span></span><span></span><span></span><span class="sr-only">Open menu</span></button><nav class="site-nav" id="site-nav" aria-label="Primary navigation"><a href="../index.html#destinations">Destinations</a><a href="#overview">Overview</a><a href="#included">What’s included</a></nav><a class="button button-primary header-cta" data-whatsapp href="#" target="_blank" rel="noopener noreferrer">Start on WhatsApp</a></header>
  <main>
    <section class="detail-hero"><img id="detail-image" src="../assets/destinations/mexico.jpg" alt="Tropical all-inclusive resort destination" width="1800" height="1200" fetchpriority="high"><div class="detail-hero-content"><a class="back-link" href="../index.html#packages">← Back to destinations</a><h1 id="detail-title">Vacation details</h1><p id="detail-intro"></p></div></section>
    <section class="detail-summary" aria-label="Package summary"><div class="summary-item"><small>Departure region</small><strong>Canada</strong></div><div class="summary-item"><small>Dates</small><strong>Subject to availability</strong></div><div class="summary-item"><small>Package style</small><strong>All-inclusive options</strong></div><div class="summary-price"><small>Starting from</small><strong data-price></strong><span>CAD · per person*</span></div><a class="button button-primary" data-whatsapp href="#" target="_blank" rel="noopener noreferrer">Ask about this trip</a></section>
    <div class="detail-main section" id="overview">
      <section class="overview-grid"><div class="detail-copy"><h2>A simple place to start.</h2><p id="detail-overview"></p><dl class="detail-facts"><div><dt>Departure</dt><dd>Major Canadian gateways</dd></div><div><dt>Airline options</dt><dd id="detail-airline"></dd></div><div><dt>Resort options</dt><dd id="detail-resort"></dd></div><div><dt>Meal plan</dt><dd id="detail-meal"></dd></div><div><dt>Travel dates</dt><dd>Dates subject to availability</dd></div></dl></div><div class="gallery" id="detail-gallery" aria-label="Destination and resort gallery"></div></section>
      <section class="detail-inclusions section" id="included"><h2>What this vacation can include.</h2><ul><li>Round-trip flight options from Canada</li><li>Resort accommodation</li><li>All-inclusive or listed meal plan</li><li>Airport-to-resort transfers</li><li>Selected resort activities</li><li>AMAX advisor support</li></ul></section>
      <section class="detail-inquiry"><div><h2>Let’s confirm the right option.</h2><p>Message AMAX with your preferred dates, departure city, traveller count and budget. We’ll return with current options.</p></div><a class="button button-primary" data-whatsapp href="#" target="_blank" rel="noopener noreferrer">Inquire on WhatsApp</a></section>
      <p class="detail-note">*Illustrative starting price in CAD, per person based on double occupancy. This page is not live inventory. Hotel, airline, dates, inclusions, taxes, availability and final price must be confirmed by an AMAX travel advisor before booking.</p>
      <nav class="detail-nav" aria-label="Other destinations"><a href="mexico.html">Mexico</a><a href="dominican-republic.html">Dominican Republic</a><a href="cuba.html">Cuba</a><a href="jamaica.html">Jamaica</a><a href="cancun.html">Cancún</a><a href="punta-cana.html">Punta Cana</a></nav>
    </div>
  </main>
  <footer class="site-footer detail-footer"><a class="brand footer-brand" href="../index.html"><img class="brand-logo" src="../assets/logo/amax-logo-color.png" alt="AMAX Vacations" width="1774" height="887"></a><p>Curated vacation ideas for travellers across Canada.</p><div class="footer-links"><a href="mailto:info@amaxtravel.ca">info@amaxtravel.ca</a><a href="tel:+14377702030">+1 437 770 2030</a></div><small>Final supplier terms and confirmed pricing apply.</small></footer>
  <a class="whatsapp-float" data-whatsapp href="#" target="_blank" rel="noopener noreferrer" aria-label="Start a WhatsApp chat with AMAX Vacations"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 11.6a8.3 8.3 0 0 1-12.3 7.3L4 20l1.1-4.1A8.3 8.3 0 1 1 20.5 11.6Z"/><path d="M8.8 8.1c.2-.4.4-.4.7-.4h.4c.1 0 .3 0 .4.3l.6 1.5c.1.2.1.3 0 .5l-.5.7c-.1.1-.2.3 0 .5.5 1 1.3 1.8 2.3 2.3.2.1.4.1.5-.1l.7-.8c.2-.2.3-.2.5-.1l1.5.7c.2.1.3.2.3.4 0 .2-.1 1.1-.7 1.6-.5.5-1.2.8-2 .7-1.3-.2-2.9-1-4.2-2.2-1.6-1.5-2.5-3.4-2.6-4.6 0-.5.2-.8.3-1Z"/></svg></a>`;
